### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by lelelexxx** [avirambh/ScopeFlow#2]
Hi!
     Thanks for sharing such an excellent work.
     I have read the paper and code of ScopeFlow, And I found something confusing problems blow:
         

1.augmentation.py  is used to perform geometry augmentation, and you have set min_rotate and max_rotate to -0.2 and 0.2. But the rotate coefficient will be generate randomly between [0.2, 0.2] such as line 261 or line 791, you set rotate coefficient to [-0.2, 0.2], but when generate random coefficent you use [-min_rotate, max_rotate], and thus rotate coefficient is generated between [0.2,0.2], which means always 0.2.
    phi.uniform_(-min_rotate, max_rotate)
     min_rotate=-1 * self._args.aug_rotate, max_rotate=self._args.aug_rotate,
     aug_rotate: 0.2     

        
2.According to the find_invalid() in file augmentation, when random generated zoom < 1.0, the affine matrix will never be valid, as if zoom<1.0, the corners of transformed img will be out of the border of source img. 
    Expecting for your replies! Thanks again!

**Comment by avirambh** [comment]
Hi @lelelexxx,
Thanks for sharing your findings and sorry for the delay! 

I see you already opened an [issue](https://github.com/visinf/irr/issues/21) in the IRR repo, for the bug in the rotation parameters, which can hopefully improve the overall performance. Did you try to fix this already? In our work we focus on the cropping and zooming parameters, since we found they have the largest effect on the sampled set of scene scopes, thus I think the effect of fixing the rotation bug should be similar as in IRR. 

Regarding 2, we found that allowing some invalid transformations is not hurting the performance, so we allowed some of them.

Thanks again!
